test-data:
  grocerycrud:
    url: "https://www.grocerycrud.com/v1.x/demo/bootstrap_theme"

selenium:
  configuration:
    timeout: "30"
    execution: "local"
  grid:
    url: "http://localhost"
    port: "4444"